#!/usr/bin/env bash
# -----------------------------------------------------
# Monitor switcher: settings
# -----------------------------------------------------
# Edit values here for day-to-day tweaks; the scripts shouldn't need to change.

# Regex matched against `hyprctl monitors` names to find the laptop
# panel. Everything else is treated as "external".
LAPTOP_NAME_PATTERN='^eDP'

DEFAULT_LAPTOP_SCALE="1"
DEFAULT_EXTERNAL_SCALE="1"

# Workspace numbers for the laptop ("primary") vs. an external
# ("secondary") monitor when both are active (Extend mode). Not enforced
# in single-monitor modes — every workspace lives on the one active
# monitor, same as Hyprland's own default.
WORKSPACES_PRIMARY=(1 2 3 4 5)
WORKSPACES_SECONDARY=(6 7 8 9 10)

ROFI_THEME="$HOME/.config/rofi/style.rasi"

# Generated by the scripts — don't hand-edit.
MONITORS_OUT="$HOME/.config/hypr/conf/monitors/current.conf"
WORKSPACES_OUT="$HOME/.config/hypr/conf/workspaces/current.conf"
