include ~/.cache/matugen/colors-kitty.conf
confirm_os_window_close 0
font_size 14
allow_remote_control yes
listen_on unix:/tmp/kitty

repaint_delay 8
input_delay 2
sync_to_monitor no

# Maps
map ctrl+shift+p launch bash -c "fzf < <(find ~ -type f)"
map ctrl+shift+t launch --type=window zsh -i
