[charger]
governor = performance
energy_performance_preference = performance
scaling_min_freq = 415000
scaling_max_freq = 5000000
turbo = auto

[battery]
governor = powersave
energy_performance_preference = balance_power
scaling_min_freq = 415000
scaling_max_freq = 2500000
turbo = auto
