[charger]
governor = performance
energy_performance_preference = balance_performance
scaling_min_freq = 415000
scaling_max_freq = 2500000
turbo = auto

[battery]
governor = powersave
energy_performance_preference = power
scaling_min_freq = 415000
scaling_max_freq = 1500000
turbo = never
