backend = "full"
color_space = "lch"
check_contrast = true
fallback_generator = "complementary"
palette = "darkcomp16"
saturate = 10

[templates]

kitty.template = 'colors-kitty.conf'
kitty.target = '~/.cache/wallust/colorFiles/kitty.conf'

hypr.template = 'colors-hypr.conf'
hypr.target = '~/.cache/wallust/colorFiles/hyprland.conf'

rofi.template = 'colors-rofi.conf'
rofi.target = '~/.cache/wallust/colorFiles/rofi.rasi'

waybar.template = 'colors-waybar.conf'
waybar.target = '~/.cache/wallust/colorFiles/waybar.css'
