splash = false
ipc = on

# Preload the image once to memory
preload = /home/simeon32/Wallpapers/AC Valhalla.jpg

# Apply to your monitors
# Using "all" is the new way to handle the wildcard
wallpaper {
    monitor = 
    path = /home/simeon32/Wallpapers/AC Valhalla.jpg
}
